[package]
name = "camouflage-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "camouflage_core"
path = "src/lib.rs"

[dependencies]
cpal.workspace = true
anyhow.workspace = true
tracing.workspace = true
dirs = "5.0"
